# Generated by Django 5.2.7 on 2026-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(choices=[('NIFTY50', 'NIFTY50'), ('RELIANCE', 'RELIANCE'), ('TCS', 'TCS'), ('INFY', 'INFY'), ('HDFCBANK', 'HDFCBANK')], max_length=20, unique=True),
        ),
    ]
