# Generated by Django 5.2.6 on 2025-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=10)),
                ('headline', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
