# Generated by Django 5.2.7 on 2026-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='asset_symbol',
            field=models.CharField(choices=[('NIFTY50', 'NIFTY50'), ('RELIANCE', 'RELIANCE'), ('TCS', 'TCS'), ('INFY', 'INFY'), ('HDFCBANK', 'HDFCBANK')], max_length=20),
        ),
    ]
