# Generated by Django 5.2.7 on 2026-04-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant_data_pipeline', '0002_alter_marketdata_asset_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('asset_symbol', 'timestamp')},
        ),
    ]
